import React,{useState,useRef,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {TASKS} from '../server/catalog.mjs';
import {makeCsv} from './csv.mjs';
import './style.css';
function App(){
 const [id,setId]=useState(''),[student,setStudent]=useState(''),[task,setTask]=useState<any>(null),[result,setResult]=useState<any>(null),[progress,setProgress]=useState('');
 const frame=useRef<HTMLIFrameElement>(null),rows=useRef<any[]>([]),attempt=useRef<any>(null),done=useRef(false);
 function download(){const url=URL.createObjectURL(new Blob([makeCsv(result)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${result.student.replace(/[^\p{L}\p{N}_-]/gu,'_')}_${result.task}_${result.run}.csv`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(task||result){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[task,result]);
 useEffect(()=>{if(!task)return;const init=()=>frame.current?.contentWindow?.postMessage({type:'TASK_INIT',payload:{participantId:student,age:'',sex:'',grade:'',session:'pre',assessorId:'',deviceId:''}},'*');const listener=(e:MessageEvent)=>{if(e.source!==frame.current?.contentWindow||!e.data||done.current)return;const m=e.data;if(m.type==='TASK_READY')init();if(m.type==='TRIAL_DATA')rows.current.push(m.trial||m.payload||{});if(m.type==='TASK_PROGRESS')setProgress(`已完成 ${m.completed}/${m.total} 题`);if(m.type==='TASK_COMPLETE'){done.current=true;if(m.status&&m.status!=='complete'){alert('本次测试未完成，请重新测试。');setTask(null);return;}setResult({...attempt.current,finished:new Date().toISOString(),summary:m.summary||m.payload||{},trials:rows.current,device:{userAgent:navigator.userAgent,width:innerWidth,height:innerHeight}});setTask(null);}};window.addEventListener('message',listener);init();return()=>window.removeEventListener('message',listener);},[task,student]);
 return <><header>认知实验 · 学生端</header><main>{!student?<section><h1>准备好，开始今天的测试。</h1><p>填写学号。完成后下载 CSV 文件，发送给老师。</p><form onSubmit={e=>{e.preventDefault();if(id.trim())setStudent(id.trim());}}><label>学号<input required maxLength={100} value={id} onChange={e=>setId(e.target.value)} autoComplete="off"/></label><button>进入测试</button></form></section>:task?<><div className="bar"><strong>{task.name} · 学号 {student}</strong><span>{progress}</span><button onClick={()=>{if(confirm('退出会丢失本次未完成的测试，确定退出？'))setTask(null);}}>退出测试</button></div><iframe ref={frame} title={task.name} src={`./tasks/${task.id}/index.html`} sandbox="allow-scripts allow-forms allow-modals allow-pointer-lock"/></>:result?<section><h1>测试已完成</h1><p>学号 {result.student} · {TASKS.find(t=>t.id===result.task)?.name}</p><p><strong>请下载 CSV，并通过微信、邮件或老师指定的方式发送文件。</strong></p><p>结果没有上传到后台。请确认文件已保存后再离开，可以重复下载。</p><button onClick={download}>下载 CSV 结果</button><button className="secondary" onClick={()=>{if(confirm('请确认已下载并保存 CSV。返回项目列表？'))setResult(null);}}>返回项目列表</button></section>:<section><h1>选择测试项目</h1><p>学号 {student} · 每完成一个项目，请下载对应 CSV。</p>{TASKS.map(t=><article key={t.id}><div><h2>{t.name}</h2><p>{t.domain} · 约 {t.minutes} 分钟</p></div><button onClick={()=>{rows.current=[];done.current=false;attempt.current={student,task:t.id,version:t.version,run:crypto.randomUUID(),started:new Date().toISOString()};setProgress('请按提示开始');setTask(t);}}>开始测试</button></article>)}<button className="secondary" onClick={()=>{setStudent('');setId('');}}>更换学号</button></section>}</main></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
